name: Cypress tests
on: [push]
jobs:
  # note: Ubuntu 16 probably works, but is deprecated

  basic-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/sample_spec.js
          browser: chrome
          headless: true